services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: ./php
      target: ${TARGET:-dev}
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    image: ${COMPOSE_PROJECT_NAME}-php-fpm:1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    environment:
      TZ: Asia/Tashkent
    volumes:
      - ./../project/:/var/www/html:rw
    depends_on:
      - db

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./nginx
    image: ${COMPOSE_PROJECT_NAME}-nginx:1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    tty: true
    environment:
      TZ: Asia/Tashkent
    ports:
      - 127.0.0.1:${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../project/:/var/www/html:rw
    depends_on:
      - php

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: "mariadb:10.5.2"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-example}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME:-example}"
      MYSQL_USER: "${DB_USER:-example}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-example}"
      TZ: Asia/Tashkent
    volumes:
      - "db_data:/var/lib/mysql"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

volumes:
  db_data:
